### ISSUE TITLE
Add gh-pages branch

### ISSUE THREAD

**Issue by AlexMunoz905** [monikarana/Money-Manager#1]
Add gh-pages branch

**Comment by AlexMunoz905** [comment]
nevermind realized this used node

**Comment by monikarana** [comment]
Hey,

Thanks for checking out my little app. I've created a gh-pages branch and have pushed a built version. You can check the demo here: http://monikarana.github.io/Money-Manager/

Thanks again!

**Comment by AlexMunoz905** [comment]
Nice :100:
